import Image from "next/image";
import styles from "./page.module.css";
import ChildComponent from "./components/ChildComponent";
import ProductCard from "./components/ProductCard";
import Categories from "./components/Categories";

export const metadata = {
  title: "Cửa hàng bánh ngọt Becky",
  description: "Generated by create next app",
};

export default async function Home() {
  const resHot = await fetch("http://localhost:3000/products/hot");
  const dataHot = await resHot.json();

  const resNew = await fetch("http://localhost:3000/products/new");
  const dataNew = await resNew.json();
  const resView = await fetch("http://localhost:3000/products/view");
  const dataView = await resView.json();

  return (
    <>
      <div className="banner">
        <div className="banner_left">
          <div className="slideshow-container">
            <div className="mySlides fade">
              <img src="images/banh1.jpg" alt="slide 1" />
            </div>
            <div className="mySlides fade">
              <img src="images/banh2.jpg" alt="slide 2" />
            </div>
            <div className="mySlides fade">
              <img src="images/banh3.jpg" alt="slide 3" />
            </div>
          </div>
        </div>
        <div className="banner_right">
          <div className="banner_right_one">
            <img src="images/banh5.webp" alt="banner right one" />
          </div>
          <div className="banner_right_two">
            <img src="images/banh6.webp" alt="banner right two" />
          </div>
        </div>
      </div>
      <div className="service">
        <div className="col-service">
          <div className="icon-service">
            <img src="images/service_img_1.webp" alt="service 1" />
          </div>
          <div className="title-service">
            <h2>Bánh tươi mỗi ngày</h2>
            <p>
              Sản phẩm được sản xuất trong ngày với nguyên liệu chất lượng và
              tươi mới
            </p>
          </div>
        </div>
        <div className="col-service">
          <div className="icon-service">
            <img src="images/service_img_2.webp" alt="service 2" />
          </div>
          <div className="title-service">
            <h2>Đa dạng chọn lựa</h2>
            <p>
              Thế giới phong phú của bánh kem tươi, bánh mì, pizza, bánh ngọt...
            </p>
          </div>
        </div>
        <div className="col-service">
          <div className="icon-service">
            <img src="images/service_img_3.webp" alt="service 3" />
          </div>
          <div className="title-service">
            <h2>Danh sách cửa hàng</h2>
            <p>
              Gần 100 cửa hàng lớn, phủ khắp các quận huyện nhằm đáp ứng nhu cầu
              mua sắm tiện lợi
            </p>
          </div>
        </div>
        <div className="col-service">
          <div className="icon-service">
            <img src="images/service_img_4.webp" alt="service 4" />
          </div>
          <div className="title-service">
            <h2>Dịch vụ tận tâm</h2>
            <p>
              Sự tỉ mỉ, tận tâm và chuyên nghiệp luôn là huyết mạch trong phục
              vụ
            </p>
          </div>
        </div>
      </div>
      <div className="products-new">
        <div className="col-catalog">
          <div className="img-catalog">
            <img src="images/hott.png" alt="hot products" />
          </div>
          <div className="name-catalog">Sản phẩm hot</div>
        </div>
        <div className="list-products" id="showSpHot">
          <ProductCard data={dataHot}></ProductCard>
        </div>
      </div>
      <div className="products-new">
        <div className="col-catalog">
          <div className="img-catalog">
            <img src="images/macaron.png" alt="new products" />
          </div>
          <div className="name-catalog">Sản phẩm mới nhất</div>
        </div>
        <div className="list-products" id="showSpNew">
          <ProductCard data={dataNew}></ProductCard>
        </div>
      </div>
      <div className="products-new">
        <div className="col-catalog">
          <div className="img-catalog">
            <img src="images/croi-png.png" alt="most viewed products" />
          </div>
          <div className="name-catalog">Sản phẩm nhiều lượt xem</div>
        </div>
        <div className="list-products" id="showSpView">
          <ProductCard data={dataView}></ProductCard>
        </div>
      </div>
      <Categories></Categories>

      <div className="news">
        <h2 className="title">TIN TỨC</h2>
        <div className="list-news">
          <div className="col-list-news">
            <div className="img-news">
              <img src="images/news.webp" alt="news 1" />
            </div>
            <div className="tintuc-content">
              <div className="title-news">
                "One small positive thought in the morning can change your whole
                day."
              </div>
              <div className="date-news">22-08-2024</div>
              <div className="text-news">
                Nguyên liệu hữu cơ, bột mì thượng hạng, kem tươi, trứng gà, sữa,
                bơ thơm ngon. Hoàn toàn tự nhiên trong từng lớp bánh và mọi thứ
                ở giữa. Không chất bảo quản, không hương vị nhân tạo và không
                Photoshop.
              </div>
              <div className="bnt-tintuc">
                <button>Đọc Thêm</button>
              </div>
            </div>
          </div>
          <div className="col-list-news">
            <div className="tintuc-content">
              <div className="title-news">
                "Share your dreams, together we build a better world."
              </div>
              <div className="date-news">23-08-2024</div>
              <div className="text-news">
                Bánh dành cho sinh nhật, đám cưới, ngày kỷ niệm, lễ tốt nghiệp,
                tiệc mừng em bé chào đời, chương trình khuyến mãi và những ngày
                đau lòng. Không chất bảo quản, không hương vị nhân tạo và không
                Photoshop.
              </div>
              <div className="bnt-tintuc">
                <button>Đọc Thêm</button>
              </div>
            </div>
            <div className="img-news">
              <img src="images/news2.webp" alt="news 2" />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
